blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/okota7412/exprefecture/discussions
    about: æŠ€è¡“çš„ãªè³ªå•ã‚„ä¸€èˆ¬çš„ãªãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ã¯ã“ã¡ã‚‰

